services:
  video-manager:
    build: .
    container_name: video-manager
    ports:
      - "3001:3001"
    env_file:
      - ./.env
  frontend:
    build: ./vxxplayer
    ports:
      - "80:80"
    depends_on:
      - video-manager
    restart: always